# TP de modélisation 2 : Pandas

## Exercice 1 : Creating and Modifying Series

Create a Pandas Series from a dictionary where keys are ['a', 'b', 'c'] and values are [100, 200, 300].

In [ ]:
 #On importe les librairies nécessaires
import numpy as np
import pandas as pd
#On crée un dictionnaire qui contient les données
dic={'A':['T','T','A','C','G','G','C'],'B':['A','A','B','C','D','D','C']}
#On crée un dataframe à partir du dictionnaire
df=pd.DataFrame(dic)
print(df)

   A  B
0  T  A
1  T  A
2  A  B
3  C  C
4  G  D
5  G  D
6  C  C

## Exercice 2 : Creating DataFrames

Create a DataFrame from the following data:

In [8]:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

IndentationError: unexpected indent (759317199.py, line 1)

Modify the code to add a new column D with values [10, 11, 12].

Drop column B from the DataFrame and display the result.

In [10]:
lists=[[1,4,7],[2,5,8],[3,6,9]]
df=pd.DataFrame(data=lists,columns=['A','B','C'])
print(df)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [16]:
df['D']=[10,11,12]
print(df)

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [18]:
#on précise le nom de la colonne à supprimer
df.drop('D',axis=1,inplace=True)
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

## Exercice 3 : DataFrame Indexing and Selection

Select column B from the following DataFrame:

In [24]:
df=pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Modify the code to select both columns A and C.

Select the row with index 1 using the .loc method.

In [25]:
#selection des colonnes A et C
df1=df[['A','C']]
df1

   A  C
0  1  3
1  4  6
2  7  9

In [26]:
#selection de la ligne avec l'index 1
df2=df.loc[1]
df2

A    4
B    5
C    6
Name: 1, dtype: int64

## Exercice 4 : Adding and Removing DataFrame Elements

Add a new column Sum to the DataFrame which is the sum of columns A, B, and C.

Remove the column Sum from the DataFrame.

Add a column Random with random numbers generated using numpy.

In [ ]:
#ajout de la colonne sum comme voulu
df['sum']=df['A']+df['B']+df['C']
df

   A  B  C  sum
0  1  2  3    6
1  4  5  6   15
2  7  8  9   24

In [ ]:
#suppression de la colonne sum
df.drop('sum',axis=1,inplace=True)
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#ajout de la colonne random
df['random']=np.random.randint(0,100,3)
df

   A  B  C  random
0  1  2  3      72
1  4  5  6      15
2  7  8  9       0

## Exercice 5 : Merging DataFrames

Merge the following two DataFrames on the key column:

In [ ]:
left:
   key  A  B
0    1  A1  B1
1    2  A2  B2
2    3  A3  B3

right:
   key  C  D
0    1  C1  D1
1    2  C2  D2
2    3  C3  D3

In [ ]:
#création des dataframes left et right
left=pd.DataFrame({'key':[1,2,3],'A':['A1','A2','A3'],'B':['B1','B2','B3']})
right=pd.DataFrame({'key':[1,2,3],'C':['C1','C2','C3'],'D':['D1','D2','D3']})
print(left) 
print(right)

   key   A   B
0    1  A1  B1
1    2  A2  B2
2    3  A3  B3
   key   C   D
0    1  C1  D1
1    2  C2  D2
2    3  C3  D3

In [32]:
#jointure interne
df1=pd.merge(left,right,on='key')
df1

   key   A   B   C   D
0    1  A1  B1  C1  D1
1    2  A2  B2  C2  D2
2    3  A3  B3  C3  D3

In [34]:
#on rajoute une colone a right
right['E']=['x','y','z']
right

   key   C   D  E
0    1  C1  D1  x
1    2  C2  D2  y
2    3  C3  D3  z

In [35]:
df1=pd.merge(left,right,on='key')
df1

   key   A   B   C   D  E
0    1  A1  B1  C1  D1  x
1    2  A2  B2  C2  D2  y
2    3  A3  B3  C3  D3  z

## Exercice 6 : Data Cleaning

Replace all NaN values in the following DataFrame with the value 0:

In [ ]:
   A    B    C
0  1.0  NaN  3.0
1  NaN  5.0  6.0
2  7.0  8.0  NaN

Modify the code to replace NaN values with the mean of the column.

Drop rows where any value is NaN.

In [36]:
df=pd.DataFrame(data=[[1,np.nan,3],[np.nan,5,6],[7,8,np.nan]],columns=['A','B','C'])
df

     A    B    C
0  1.0  NaN  3.0
1  NaN  5.0  6.0
2  7.0  8.0  NaN

In [ ]:
#remplacement des valeurs manquantes par la moyenne
for a in df.columns:
    df[a].fillna(df[a].mean(),inplace=True)
df

C:\Users\Seriwawa\AppData\Local\Temp\ipykernel_8632\2301697293.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[a].fillna(df[a].mean(),inplace=True)

     A    B    C
0  1.0  6.5  3.0
1  4.0  5.0  6.0
2  7.0  8.0  4.5

In [41]:
df=pd.DataFrame(data=[[1,2,3],[np.nan,5,6],[7,8,np.nan]],columns=['A','B','C'])
df

     A  B    C
0  1.0  2  3.0
1  NaN  5  6.0
2  7.0  8  NaN

In [ ]:
#suppression des lignes avec des valeurs manquantes
df.dropna(axis=0,inplace=True)
df

     A  B    C
0  1.0  2  3.0

## Exercice 7 : Grouping and Aggregation

Group the following DataFrame by column Category and calculate the mean of column Value:

In [ ]:
   Category  Value
0         A      1
1         B      2
2         A      3
3         B      4
4         A      5
5         B      6

In [43]:
df=pd.DataFrame(data={'Catégorie':['A','B','A','B','A','B'],'Value':[1,2,3,4,5,6]})
df

  Catégorie  Value
0         A      1
1         B      2
2         A      3
3         B      4
4         A      5
5         B      6

In [54]:
#Calcul de l'effectif de chaque catégorie
df.groupby('Catégorie')['Catégorie'].value_counts()

Catégorie
A    3
B    3
Name: count, dtype: int64

In [52]:
#calcul de la moyenne des valeurs pour chaque catégorie
df.groupby('Catégorie')['Value'].mean()

Catégorie
A    3.0
B    4.0
Name: Value, dtype: float64

## Exercice 8 : Pivot Tables

Create a pivot table from the following DataFrame, showing the mean Value for each Category and Type:

In [ ]:
   Category  Type  Value
0         A     X      1
1         A     Y      2
2         A     X      3
3         B     Y      4
4         B     X      5
5         B     Y      6

Modify the pivot table to show the sum of Value instead of the mean.

Add margins to the pivot table to show the total mean for each Category and Type.

In [55]:
df=pd.DataFrame(data={'Catégorie':['A','A','A','B','B','B'],'Type':['X','Y','X','Y','X','Y'],'Value':[1,2,3,4,5,6]})
df

  Catégorie Type  Value
0         A    X      1
1         A    Y      2
2         A    X      3
3         B    Y      4
4         B    X      5
5         B    Y      6

In [ ]:
#on crée une table pivot avec comme fonction d'agregation la moyenne et value comme valeur
pivot=df.pivot_table(index='Catégorie',columns='Type',values='Value',aggfunc='mean')
pivot

Type         X    Y
Catégorie
A          2.0  2.0
B          5.0  5.0

In [60]:
#somme a la place de la moyenne
pivot=df.pivot_table(index='Catégorie',columns='Type',values='Value',aggfunc='sum')
pivot

Type       X   Y
Catégorie
A          4   2
B          5  10

In [61]:
# rajout des totaux avec margins=True
pivot=df.pivot_table(index='Catégorie',columns='Type',values='Value',aggfunc='sum',margins=True)
pivot

Type       X   Y  All
Catégorie
A          4   2    6
B          5  10   15
All        9  12   21

## Exercice 9 : Time Series Data

Create a time series DataFrame with a date range starting from '2023-01-01' for 6 periods and random values.

Set the date column as the index of the DataFrame.

Resample the data to calculate the sum for each 2-day period.

In [73]:
#on crée un dataframe avec 365 jours à partir du 1er janvier 2023
periods=pd.date_range(start='2023-01-01',periods=265,freq='D')
periods
randomdates=np.random.choice(periods,6,replace=False)
randomdates
randomdatesdf=pd.to_datetime(randomdates)
randomdatesdf
df1=pd.DataFrame(data=randomdatesdf,columns=['Date'])
df1

        Date
0 2023-09-05
1 2023-03-01
2 2023-08-18
3 2023-08-08
4 2023-06-01
5 2023-01-06

In [74]:
#On change l'index
df1.set_index('Date',inplace=True)
df1

Empty DataFrame
Columns: []
Index: [2023-09-05 00:00:00, 2023-03-01 00:00:00, 2023-08-18 00:00:00, 2023-08-08 00:00:00, 2023-06-01 00:00:00, 2023-01-06 00:00:00]

In [ ]:
#on ressessemple pour avoir toutes les dates avec eccart
resampled_df = df1.resample('2D').sum()
resampled_df

Empty DataFrame
Columns: []
Index: [2023-01-06 00:00:00, 2023-01-08 00:00:00, 2023-01-10 00:00:00, 2023-01-12 00:00:00, 2023-01-14 00:00:00, 2023-01-16 00:00:00, 2023-01-18 00:00:00, 2023-01-20 00:00:00, 2023-01-22 00:00:00, 2023-01-24 00:00:00, 2023-01-26 00:00:00, 2023-01-28 00:00:00, 2023-01-30 00:00:00, 2023-02-01 00:00:00, 2023-02-03 00:00:00, 2023-02-05 00:00:00, 2023-02-07 00:00:00, 2023-02-09 00:00:00, 2023-02-11 00:00:00, 2023-02-13 00:00:00, 2023-02-15 00:00:00, 2023-02-17 00:00:00, 2023-02-19 00:00:00, 2023-02-21 00:00:00, 2023-02-23 00:00:00, 2023-02-25 00:00:00, 2023-02-27 00:00:00, 2023-03-01 00:00:00, 2023-03-03 00:00:00, 2023-03-05 00:00:00, 2023-03-07 00:00:00, 2023-03-09 00:00:00, 2023-03-11 00:00:00, 2023-03-13 00:00:00, 2023-03-15 00:00:00, 2023-03-17 00:00:00, 2023-03-19 00:00:00, 2023-03-21 00:00:00, 2023-03-23 00:00:00, 2023-03-25 00:00:00, 2023-03-27 00:00:00, 2023-03-29 00:00:00, 2023-03-31 00:00:00, 2023-04-02 00:00:00, 2023-04-04 00:00:00, 2023-04-06 00:00:00, 2023-04-08 00:00:00, 2023-04-10 00:00:00, 2023-04-12 00:00:00, 2023-04-14 00:00:00, 2023-04-16 00:00:00, 2023-04-18 00:00:00, 2023-04-20 00:00:00, 2023-04-22 00:00:00, 2023-04-24 00:00:00, 2023-04-26 00:00:00, 2023-04-28 00:00:00, 2023-04-30 00:00:00, 2023-05-02 00:00:00, 2023-05-04 00:00:00, 2023-05-06 00:00:00, 2023-05-08 00:00:00, 2023-05-10 00:00:00, 2023-05-12 00:00:00, 2023-05-14 00:00:00, 2023-05-16 00:00:00, 2023-05-18 00:00:00, 2023-05-20 00:00:00, 2023-05-22 00:00:00, 2023-05-24 00:00:00, 2023-05-26 00:00:00, 2023-05-28 00:00:00, 2023-05-30 00:00:00, 2023-06-01 00:00:00, 2023-06-03 00:00:00, 2023-06-05 00:00:00, 2023-06-07 00:00:00, 2023-06-09 00:00:00, 2023-06-11 00:00:00, 2023-06-13 00:00:00, 2023-06-15 00:00:00, 2023-06-17 00:00:00, 2023-06-19 00:00:00, 2023-06-21 00:00:00, 2023-06-23 00:00:00, 2023-06-25 00:00:00, 2023-06-27 00:00:00, 2023-06-29 00:00:00, 2023-07-01 00:00:00, 2023-07-03 00:00:00, 2023-07-05 00:00:00, 2023-07-07 00:00:00, 2023-07-09 00:00:00, 2023-07-11 00:00:00, 2023-07-13 00:00:00, 2023-07-15 00:00:00, 2023-07-17 00:00:00, 2023-07-19 00:00:00, 2023-07-21 00:00:00, 2023-07-23 00:00:00, ...]

[122 rows x 0 columns]

## Exercice 10 : Handling Missing Data

Interpolate missing values in the following DataFrame:

In [ ]:
   A    B    C
0  1.0  NaN  3.0
1  2.0  5.0  NaN
2  NaN  8.0  9.0

In [77]:
df=pd.DataFrame(data=[[1,2.0,np.nan],[np.nan,5,6],[3,np.nan,9]],columns=['A','B','C'])
df

     A    B    C
0  1.0  2.0  NaN
1  NaN  5.0  6.0
2  3.0  NaN  9.0

In [ ]:
#interpolation
df.interpolate(method='linear',order=2,inplace=True)
df.fillna(method='bfill',inplace=True)
df

C:\Users\Seriwawa\AppData\Local\Temp\ipykernel_8632\2394753315.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill',inplace=True)

     A    B    C
0  1.0  2.0  6.0
1  2.0  5.0  6.0
2  3.0  5.0  9.0

In [87]:
df=pd.DataFrame(data=[[1,2.0,np.nan],[np.nan,5,6],[3,np.nan,9]],columns=['A','B','C'])
df

     A    B    C
0  1.0  2.0  NaN
1  NaN  5.0  6.0
2  3.0  NaN  9.0

In [93]:
#supprimer une colonne si on a un na
df.dropna(axis=0,inplace=True)
df

Empty DataFrame
Columns: []
Index: [0, 1, 2]

## Exercice 11 : DataFrame Operations

Calculate the cumulative sum of the following DataFrame:

In [ ]:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df=pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'])
#ajout de la somme des lignes
df['sum']=df.sum(axis=1)
#ajout de la somme des colonnes 
df.loc['Total']=df.sum()
df

        A   B   C  sum
0       1   2   3    6
1       4   5   6   15
2       7   8   9   24
Total  12  15  18   45

Calculate the cumulative product of the DataFrame.

Apply a function to subtract 1 from all elements in the DataFrame.

In [ ]:
#calcul du produit cumulé
# df prod calcile le produit des colonnes puis le produit des résultats
dfcumprod=df.prod().prod()
dfcumprod

np.int64(1847123066880000)

In [ ]:
#ajout de 1 à chaque élément
df=df+1
df

        A   B   C  sum
0       2   3   4    7
1       5   6   7   16
2       8   9  10   25
Total  13  16  19   46